---
- hosts: all
  become: yes
  vars:
    filebeat_yml: /etc/filebeat/filebeat.yml
    filebeat_connections:
    - localhost:5044
    filebeat_version: 7.7.1
  
  roles:
  - filebeat
  
  handlers:
  - name: Restart filebeat
    service: 
      name: filebeat
      enabled: yes
      state: restarted

